In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
np.random.normal(0, 1, (10, 3))

array([[-0.5649345 , -0.66459974,  1.3157613 ],
       [ 1.36759913, -0.65765207,  0.23514372],
       [-0.17359215,  1.18837042, -1.2215716 ],
       [-0.39846206, -0.07121298,  0.84938735],
       [-0.37166915, -0.34529254, -0.78923415],
       [ 1.61027222,  0.66863774, -0.70020673],
       [-0.94007018, -0.69775067, -1.47216013],
       [ 0.03789733,  0.15624505, -0.52502429],
       [ 0.93064103, -0.17359604, -1.82690964],
       [-1.13514871,  0.36561859, -2.35275526]])

In [14]:
rng = np.random.default_rng(9)

In [15]:
normal_dist = rng.normal(0, 1, (10, 3))
normal_dist

array([[-0.80283694,  0.24284991, -1.65634543],
       [ 0.65610488,  1.14345302, -0.452611  ],
       [ 0.43048575,  0.25093257, -0.39435206],
       [-0.86240487, -2.03255243,  1.41042348],
       [-0.04763224,  2.52232741,  0.82621825],
       [ 0.27778053, -0.65743106,  1.3924692 ],
       [-0.50628911,  1.56994913, -0.39836128],
       [ 0.18595393, -1.5226704 ,  2.34323238],
       [-0.09402583, -0.38511359,  0.81084763],
       [-0.89137184,  0.76760728, -1.1712404 ]])

In [17]:
normal_dist.cumsum(axis=1)

array([[-0.80283694, -0.55998703, -2.21633246],
       [ 0.65610488,  1.7995579 ,  1.3469469 ],
       [ 0.43048575,  0.68141831,  0.28706626],
       [-0.86240487, -2.89495729, -1.48453381],
       [-0.04763224,  2.47469517,  3.30091342],
       [ 0.27778053, -0.37965053,  1.01281867],
       [-0.50628911,  1.06366002,  0.66529874],
       [ 0.18595393, -1.33671647,  1.00651591],
       [-0.09402583, -0.47913942,  0.33170822],
       [-0.89137184, -0.12376456, -1.29500497]])

In [24]:
np.zeros((10, 1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [26]:
np.concatenate([np.zeros((10, 1)), normal_dist.cumsum(axis=1)], axis=1) 

array([[ 0.        , -0.80283694, -0.55998703, -2.21633246],
       [ 0.        ,  0.65610488,  1.7995579 ,  1.3469469 ],
       [ 0.        ,  0.43048575,  0.68141831,  0.28706626],
       [ 0.        , -0.86240487, -2.89495729, -1.48453381],
       [ 0.        , -0.04763224,  2.47469517,  3.30091342],
       [ 0.        ,  0.27778053, -0.37965053,  1.01281867],
       [ 0.        , -0.50628911,  1.06366002,  0.66529874],
       [ 0.        ,  0.18595393, -1.33671647,  1.00651591],
       [ 0.        , -0.09402583, -0.47913942,  0.33170822],
       [ 0.        , -0.89137184, -0.12376456, -1.29500497]])